Add resume functionality
dani-garcia/rust_async_ftp pull request #11
Opened 2021-11-04 16:47 UTC by mihaigalos

This PR implements the "REST" FTP verb, enabling resume of partially downloaded files.

2021-11-04 16:48 UTC, mihaigalos commented
Would a static review suffice, since we are essentially just sending the remote endpoint text commands?

2021-11-04 19:44 UTC, dani-garcia requested changes
You need to declare the function as async and make sure to await the other async calls, otherwise it looks pretty straightforward.

2021-11-04 19:44 UTC, dani-garcia commented on src/ftp.rs
> +    pub fn restart_from(&mut self, offset: u64) -> crate::Result<()> {
```suggestion
    pub async fn restart_from(&mut self, offset: u64) -> Result<()> {
```

2021-11-04 19:44 UTC, dani-garcia commented on src/ftp.rs
> +        self.write_str(&rest_command)?;
```suggestion
        self.write_str(&rest_command).await?;
```

2021-11-04 19:44 UTC, dani-garcia commented on src/ftp.rs
> +        self.read_response(status::REQUEST_FILE_PENDING).map(|_| ())
```suggestion
        self.read_response(status::REQUEST_FILE_PENDING).await.map(|_| ())
```

2021-11-04 20:56 UTC, dani-garcia approved these changes

2021-11-04 20:57 UTC, merged

2021-11-04 20:57 UTC, dani-garcia commented
Thanks!

2021-11-04 21:02 UTC, mihaigalos commented
No problem. How will the version be bumped to crates.io ?
Would like to consume these changes through cargo.

2021-11-04 21:54 UTC, dani-garcia commented
I made a release now with your changes and some other small changes I had pending, as 5.1.0.
I've also updated tokio_rustls, which is an API break if you are using the secure feature, released as 6.0.0

2021-11-05 05:37 UTC, mihaigalos commented
Awesome. Thank you.